all: fix dependency on iptables meta package
APK on snapshot exposes all kinds of old dependency issues.
Here it's that the iptables/iptables6 meta package has been
deprecated for years. (Also need to fix the same in olsrd.)

ERROR: unable to select packages:
  ip6tables (virtual):
    note: please select one of the 'provided by'
          packages explicitly
    provided by: ip6tables-nft
                 ip6tables-zz-legacy
    required by: world[ip6tables]
                 olsrd-2024.06.09~d72be9ad-r1[ip6tables]
  iptables (virtual):
    note: please select one of the 'provided by'
          packages explicitly
    provided by: iptables-nft iptables-zz-legacy
    required by: olsrd-2024.06.09~d72be9ad-r1[iptables]